site_name: datasink documentation
site_description: datasink provides parallel I/O on a parallel file system from multiple, independent processes
site_author: Geert Jan Bex (geertjan.bex@uhasselt.be)
pages:
- Introduction and motivation: 'index.md'
- Use case: 'usage.md'
- Sink file description: 'sink_file.md'
- Contact information: 'contact.md'
site_dir: html_docs/datasink
theme: readthedocs
